### ISSUE TITLE
Needs Test Cases

### ISSUE THREAD

**Issue by weaksauce** [Jitsusama/UInt128#1]
Perhaps a few tests of the boundary conditions would give people more faith in the project?

**Comment by Jitsusama** [comment]
I agree. I need to learn how to properly design test cases and then I'd get right on that.

**Comment by Jitsusama** [comment]
If you could give me some pointers on proper test case construction that would be groovy.

**Comment by Jitsusama** [comment]
As an FYI; I've started building out a number of test cases. I'm currently covering about 75% of the code, but I'm planning on making it all the way into the high 90s before I stop and will then mark this issue as closed.

**Comment by Jitsusama** [comment]
83% code coverage.

**Comment by Jitsusama** [comment]
88% code coverage.

**Comment by Jitsusama** [comment]
93% code coverage.

**Comment by Jitsusama** [comment]
100% code coverage is complete. I believe I'm covering every fringe case and I have double checked that the tested expectations meet what the operation would equal if performed manually. I'm now marking this as resolved.
