### ISSUE TITLE
can't find Instance method 'fromUnparsedString' in swift3.2 branch

### ISSUE THREAD

**Issue by KarlZeo** [Jitsusama/UInt128#11]
I use swift3.2 branch,but i can't find `fromUnparsedString` this Instance method.

**Comment by Jitsusama** [comment]
Hello @KarlZeo 

I do believe that method is missing right now. The Swift 3.2 branch is currently a major deviation from the master branch's API. I'm focusing on the bare minimum to support Swift 3.2, removing a lot of older API.

That said, I am thinking about reintroducing some of it. I will admit, I wasn't expecting anyone to be using `fromUnparsedString` directly. I guess that's what I get for not marking it as private! 😄 

Let me mull this over a bit. I was thinking of removing that method, but if it is seeing use, I could entertain keeping it around for a while. Are there any other methods that you're used to using that are missing?

**Comment by KarlZeo** [comment]
Hi, @Jitsusama 
I use [NEKit](https://github.com/zhuhaow/NEKit),this repo is use your code.And some IPRange method use `fromUnparsedString` this method.

**Comment by Jitsusama** [comment]
I see that they copied over UInt128.swift into their source. I'll take a closer look when I get the basic Swift 3.2 functionality working in the swift3.2 branch. I'm thinking that I'll probably reintroduce the method and mark it as deprecated to give that project time to implement API changes in this library.

**Comment by KarlZeo** [comment]
@Jitsusama OK,Thanks.

**Comment by Jitsusama** [comment]
I just committed e28166f which reintroduces this method as deprecated. Anyone compiling code referencing `fromUnparsedString(_: String)` in Swift 3.2+ will get a warning, but the code will still compile. Could you please try this out and let me know if it works for you?

**Comment by Jitsusama** [comment]
Hello @KarlZeo, have you had a chance to try this out?

**Comment by Jitsusama** [comment]
I'm closing this out, as it should be resolved.
