### ISSUE TITLE
Not correct work: significantBits

### ISSUE THREAD

**Issue by somenkovnikita** [Jitsusama/UInt128#12]
```swift
let number = UInt128(4294967294)

//expected: number.significantBits == 31
//actually: number.significantBits == 32
```
quick fix:
```diff
--- significantBitCount += 1
+++ significantBitCount += UInt128(bitsToWalk & 1) 
```

**Comment by Jitsusama** [comment]
Thanks for sharing! Just to verify, what branch are you experiencing this issue on?

**Comment by Jitsusama** [comment]
Oh, wait, look at the following

```swift
  2> String(UInt64(4294967294), radix: 2)
$R1: String = "11111111111111111111111111111110"
```

When I count up the bits, I see 32. The way I understand the term significant bits, it refers to the amount of bits in the underlying type storage that have significance in determining the stored value. The last 0 is just as important as the preceding 31 bits, so I believe I'm giving the correct answer (32) in the case you present.

Does your understanding of significant bits differ from mine? And if so, could you explain why you would expect something different? Swift 3.2/4.0 has another property called `nonzeroBitCount` which seems to more fall in line with your expectation. My swift3.2 branch contains an implementation of this property.

**Comment by somenkovnikita** [comment]
@Jitsusama Sorry! I really did not understand the meaning correctly. 
I am using _**master**_ branch.

**Comment by Jitsusama** [comment]
No worries @somenkovnikita, would you agree that there is no bug at this time then?

**Comment by somenkovnikita** [comment]
@Jitsusama Yes, I is no bug)
