### ISSUE TITLE
ArithmeticOverflow has been deleted

### ISSUE THREAD

**Issue by humiaozuzu** [Jitsusama/UInt128#13]
from this PR, ArithmeticOverflow was remove so the swift4 branch do not compile
https://github.com/apple/swift/pull/11203

**Comment by Jitsusama** [comment]
Hello @humiaozuzu, @jackmelb's PR has resolved this issue. Please give it a try and let me know if it doesn't work for you.

**Comment by Jitsusama** [comment]
If this doesn't work for you, let me know and we can reopen this issue.
