### ISSUE TITLE
swift 3.0

### ISSUE THREAD

**Issue by renanyoy** [Jitsusama/UInt128#2]
any swift 3.0 version ?

**Comment by Jitsusama** [comment]
Not yet, but thanks for the reminder. I've been meaning to make it Swift 3.0 compliant. I'll get to work on that.

**Comment by Jitsusama** [comment]
I just pushed up v0.3.0. It passes tests and should be Swift 3.0 ready. Let me know if you run into any problems with it.

**Comment by renanyoy** [comment]
thanks, all seems fine :)

**Comment by Jitsusama** [comment]
Nice to hear! If you find anything else lacking, feel free to open up more tickets!
