### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by Usipov** [Jitsusama/UInt128#26]
Hey! Thanks for the tool.
Could you add a Podspec for your library?

**Comment by Jitsusama** [comment]
I could probably manage.  Would you mind taking a first crack at it and submit as a PR?

**Comment by jzau** [comment]
I will submit a PR ASAP

**Comment by Jitsusama** [comment]
Thanks to @jzau we have a pod spec now! I’m going to try and push UInt128 up to the Cocoapod trunk sometime this weekend.

**Comment by Jitsusama** [comment]
Alright, we should now be golden!

```
jitsusama@Joshua ~/D/UInt128> pod trunk push UInt128.podspec 
Updating spec repo `master`
Validating podspec
 -> UInt128 (0.8.0)

Updating spec repo `master`

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  UInt128 (0.8.0) successfully published
 📅  April 14th, 22:33
 🌎  https://cocoapods.org/pods/UInt128
 👍  Tell your friends!
--------------------------------------------------------------------------------
```

Please try it out and let me know if you run into any problems. I'm finding integrating a project with CocoaPods to be quite a bit confusing, so I'd like to hear from someone who knows how to do it right that UInt128 actually works through it's new pod :)

**Comment by Jitsusama** [comment]
@jzau, @Usipov; have you had a chance to test this out?

**Comment by jzau** [comment]
@Jitsusama It works, it would be good if you could add installation guide in readme, like add `pod 'UInt128'` in Podfile

**Comment by Jitsusama** [comment]
Could you please give me a basic run-down of how to properly use it? I had a hard time getting it to work myself honestly.
