### ISSUE TITLE
Add UInt128.max

### ISSUE THREAD

**Issue by dsperling** [Jitsusama/UInt128#32]
It would be handy to create a static variable to access the maximum 128 bit unsigned integer.
Similar to:
https://developer.apple.com/documentation/swift/uint64/1538705-max

Workaround is to use:
```
let maxValue = UInt128(upperBits: 0xFFFFFFFFFFFFFFFF, lowerBits: 0xFFFFFFFFFFFFFFFF)
// or
let maxValue: UInt128 = "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
```

**Comment by dsperling** [comment]
Never mind.  UInt128.max is already here.

**Comment by Jitsusama** [comment]
@dsperling; glad you figured that out. We used to have it explicit, but I believe with Swift 4 we're getting it for free from one of the protocols we implement.
