### ISSUE TITLE
Unable to add with package manager

### ISSUE THREAD

**Issue by matejukmar** [Jitsusama/UInt128#35]
I've added this line in dependencies
`.package(url: "https://github.com/Jitsusama/UInt128.git", from: "0.8.0")`

but I'm getting this error when resolving a package:
`error: the package dependency graph could not be resolved; unable to find any available tag for the following requirements:
https://github.com/Jitsusama/UInt128.git @ 0.8.0..<1.0.0`

I checked tags and both are there "0.8.0" and "v0.8.0", a bit strange ... what could be the issue?

**Comment by Jitsusama** [comment]
I believe I added the 0.8.0 tag for CocoaPods, but TBH, it's been quite some time and I can't remember exactly. I believe the from statement there can match any tag, and I'm not sure why it would complain. That said, I've never actually used this project via the Swift package manager except for testing it out, and that was over a year ago I believe.

Would you mind doing some research, find out if there is something wrong with this project and it working with newer versions of the Swift Package manager, and perhaps creating a PR (if it's a code issue), or replying with more details here?

**Comment by Jitsusama** [comment]
Closing due to age.
