### ISSUE TITLE
No build scheme for iOS platform

### ISSUE THREAD

**Issue by guoxiaoqiao** [Jitsusama/UInt128#8]
Because no build scheme for iOS platform,  project depend UInt128 with Carthage will produce following error

Module file's minimum deployment target is ios11.0 v11.0

**Comment by Jitsusama** [comment]
@guoxiaoqiao; please see my comments on PR #10. It looks like things should work with Carthage as they are. Take a look at my comments and let me know if I'm missing something.

**Comment by Jitsusama** [comment]
Hello @guoxiaoqiao,

I have rebased the swift3.2 branch against your merged pull request. I've also included additional build targets targeting the minimum supported OS version for watchOS and tvOS, while also lowering the version for macOS.

If you could try configuring Carthage to pull from the swift3.2 branch using `carthage update` which will hopefully pull in the rebase without issue and let me know if it works for your, that would be greatly appreciated.

**Comment by guoxiaoqiao** [comment]
@Jitsusama Thank you for your effort. The new build target work fine for me, both master and swift3.2 branch, but I just test with iOS target.

**Comment by Jitsusama** [comment]
Thanks for your help with this @guoxiaoqiao!
